### ISSUE TITLE
GetWeatherUseCaseImpl is in Domain module

### ISSUE THREAD

**Issue by andersbelles** [cobeisfresh/CleanArchitecture-Android-Showcase#6]
Since our Data module is supposed to contain implementations of what we have defined in Domain module. So the question is: Why is GetWeatherUseCaseImpl in the Domain module?

**Comment by LukaKordic** [comment]
> Since our Data module is supposed to contain implementations of what we have defined in Domain module.

The Data module is supposed to contain implementations of the Repository. And the reason we put the Repository interface in the domain module is because of the dependency inversion principle, so our UseCase classes can call the repository. 
The UseCases themselves are in the domain module because they represent the business logic of the app. 
Did that clarify things for you?
